eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://node2:8082/eureka/,http://node3:8083/eureka/
    instance:
        hostname: node1
server:
    port: 8081
spring:
    application:
        name: Spring-Cloud
