eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/
    instance:
        hostname: node3
server:
    port: 8083
spring:
    application:
        name: Spring-Cloud
