eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://node1:8081/eureka/,http://node3:8083/eureka/
    instance:
        hostname: node2
server:
    port: 8082
spring:
    application:
        name: Spring-Cloud
