eureka:
    client:
        serviceUrl:
            defaultZone: http://node1:8081/eureka/,http://node2:8082/eureka/,http://node3:8083/eureka/
server:
    port: 8000
spring:
    application:
        name: Provider
Provider:
    name: provide0