server:
    port: 8000
spring:
    application:
        name: gateway

zuul:
    prefix: /api
    routes:
        multiplications:
            path: /multiplications/**
            servuceId: multiplication
            strip-prefix: false
        results:
            path: /results/**
            serviceId: multiplication
            strip-prefix: false
        leaders:
            path: /leaders/**
            serviceId: gamification
            strip-prefix: false
    eureka:
        client:
            service-url:
                default-zone: http://localhost:8761/eureka/
    enpoints:
        routes:
            sensitive: false
    ignored-services: '*'
