server:
    port: 8000
spring:
    application:
        name: gateway

zuul:
    prefix: /api
    routes:
        multiplications:
            path: /multiplications/**
            url: http://localhost:8018/multiplicatons
        results:
            path: /results/**
            url: http://localhost:8018/results
        leaders:
            path: /leaders/**
            url: http://localhost:8081/leaders
        stats:
            path: /stats/**
            url: http://localhost:8081/stats
    enpoints:
        trace:
            sensitive: false
    ribbon:
        eureka:
            enabled: false
